/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import database.DataBase;
import items.Flight;
import contoller.FlightTableController;
import contoller.TableController;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import utils.GuiUtils;

/**
 *
 * @author Cedric Jansen
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateFlightDialogue = new javax.swing.JDialog();
        updateFlightDialogueContentPane = new javax.swing.JPanel();
        updateFlightDialogueContentInner = new javax.swing.JPanel();
        updateFlightDialogueTitle = new javax.swing.JLabel();
        updateFlightDialogueName = new javax.swing.JLabel();
        updateFlightDialogueID = new javax.swing.JLabel();
        updateFlightDialogueStart = new javax.swing.JLabel();
        updateFlightDialogueDest = new javax.swing.JLabel();
        updateFlightDialogueDescription = new javax.swing.JLabel();
        updateFlightDialogueNameInput = new javax.swing.JTextField();
        updateFlightDialogueIDInput = new javax.swing.JTextField();
        updateFlightDialogueStartInput = new javax.swing.JTextField();
        updateFlightDialogueDestInput = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        navPane = new javax.swing.JPanel();
        overviewButton = new javax.swing.JButton();
        flightButton = new javax.swing.JButton();
        dishesButton = new javax.swing.JButton();
        groupLabel = new javax.swing.JLabel();
        contentPane = new javax.swing.JPanel();
        flightContentPane = new javax.swing.JPanel();
        flightTablePane = new javax.swing.JPanel();
        flightTableInnerPane = new javax.swing.JPanel();
        flightScrollPane = new javax.swing.JScrollPane();
        flightTable = new javax.swing.JTable();
        flightOverviewPane = new javax.swing.JPanel();
        flightOverview = new javax.swing.JPanel();
        flightOverviewTitle = new javax.swing.JLabel();
        flightOverviewContent = new javax.swing.JPanel();
        flightOverviewActions = new javax.swing.JPanel();
        flightOverviewActionsDelete = new javax.swing.JButton();
        flightOverviewActionsUpdate = new javax.swing.JButton();
        flightOverviewActionsFeedbackPane = new javax.swing.JPanel();
        flightOverviewID = new javax.swing.JPanel();
        flightOverviewIDLabel = new javax.swing.JLabel();
        flightOverviewIDContent = new javax.swing.JLabel();
        flightOverviewStartDest = new javax.swing.JPanel();
        flightOverviewStartLabel = new javax.swing.JLabel();
        flightOverviewStartContent = new javax.swing.JLabel();
        flightOverviewDestContent = new javax.swing.JLabel();
        flightOverviewDestLabel = new javax.swing.JLabel();
        overviewContentPane = new javax.swing.JPanel();
        overviewPane = new javax.swing.JPanel();
        overviewContent = new javax.swing.JPanel();
        accessTaskPanel = new javax.swing.JPanel();
        quickAccess = new javax.swing.JPanel();
        quickAcessLabel = new javax.swing.JLabel();
        quickAccessTabPane = new javax.swing.JTabbedPane();
        quickAccessFlightTab = new javax.swing.JPanel();
        quickAccessFlightCreateButton = new javax.swing.JButton();
        quickAccessFlightDeleteButton = new javax.swing.JButton();
        quickAccessDishTab = new javax.swing.JPanel();
        quickAccessDishCreateButton = new javax.swing.JButton();
        quickAccessDishDeleteButton = new javax.swing.JButton();
        lastTasks = new javax.swing.JPanel();
        taskLabel = new javax.swing.JLabel();
        taskScrollPane = new javax.swing.JScrollPane();
        taskScrollPanel = new javax.swing.JPanel();
        taskPanel = new javax.swing.JPanel();
        taskPanelContent = new javax.swing.JLabel();
        taskPanel1 = new javax.swing.JPanel();
        taskPanelContent1 = new javax.swing.JLabel();
        taskPanel2 = new javax.swing.JPanel();
        taskPanelContent2 = new javax.swing.JLabel();
        taskPanel3 = new javax.swing.JPanel();
        taskPanelContent3 = new javax.swing.JLabel();
        taskPanel4 = new javax.swing.JPanel();
        taskPanelContent4 = new javax.swing.JLabel();
        dishContentPane = new javax.swing.JPanel();
        dishTablePane = new javax.swing.JPanel();
        dishTable = new javax.swing.JPanel();
        dishOverviewPane = new javax.swing.JPanel();
        dishOverview = new javax.swing.JPanel();
        dishOverviewTitle = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        updateFlightDialogue.setTitle("Update Flight");
        updateFlightDialogue.setAlwaysOnTop(true);
        updateFlightDialogue.setMinimumSize(new java.awt.Dimension(400, 500));
        updateFlightDialogue.setType(java.awt.Window.Type.POPUP);

        updateFlightDialogueContentInner.setBackground(new java.awt.Color(255, 255, 255));

        updateFlightDialogueTitle.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        updateFlightDialogueTitle.setText("Update");

        updateFlightDialogueName.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        updateFlightDialogueName.setText("Name:");

        updateFlightDialogueID.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        updateFlightDialogueID.setText("ID.");

        updateFlightDialogueStart.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        updateFlightDialogueStart.setText("Start Airport:");

        updateFlightDialogueDest.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        updateFlightDialogueDest.setText("Destination:");

        updateFlightDialogueDescription.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        updateFlightDialogueDescription.setText("Every input, that is not edited, will not be updated.");
        updateFlightDialogueDescription.setOpaque(true);

        updateFlightDialogueNameInput.setBackground(new java.awt.Color(240, 240, 240));
        updateFlightDialogueNameInput.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N
        updateFlightDialogueNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFlightDialogueNameInputActionPerformed(evt);
            }
        });

        updateFlightDialogueIDInput.setBackground(new java.awt.Color(240, 240, 240));
        updateFlightDialogueIDInput.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N

        updateFlightDialogueStartInput.setBackground(new java.awt.Color(240, 240, 240));
        updateFlightDialogueStartInput.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N

        updateFlightDialogueDestInput.setBackground(new java.awt.Color(240, 240, 240));
        updateFlightDialogueDestInput.setFont(new java.awt.Font("Roboto Condensed", 0, 11)); // NOI18N

        javax.swing.GroupLayout updateFlightDialogueContentInnerLayout = new javax.swing.GroupLayout(updateFlightDialogueContentInner);
        updateFlightDialogueContentInner.setLayout(updateFlightDialogueContentInnerLayout);
        updateFlightDialogueContentInnerLayout.setHorizontalGroup(
            updateFlightDialogueContentInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateFlightDialogueContentInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateFlightDialogueContentInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateFlightDialogueContentInnerLayout.createSequentialGroup()
                        .addGroup(updateFlightDialogueContentInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(updateFlightDialogueTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateFlightDialogueName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateFlightDialogueID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateFlightDialogueStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateFlightDialogueDest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(updateFlightDialogueContentInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateFlightDialogueNameInput)
                            .addComponent(updateFlightDialogueIDInput)
                            .addComponent(updateFlightDialogueStartInput)
                            .addComponent(updateFlightDialogueDestInput)))
                    .addComponent(updateFlightDialogueDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                .addContainerGap())
        );
        updateFlightDialogueContentInnerLayout.setVerticalGroup(
            updateFlightDialogueContentInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateFlightDialogueContentInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateFlightDialogueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateFlightDialogueContentInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFlightDialogueName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateFlightDialogueNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateFlightDialogueContentInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFlightDialogueID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateFlightDialogueIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateFlightDialogueContentInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFlightDialogueStart, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateFlightDialogueStartInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateFlightDialogueContentInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateFlightDialogueDest, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateFlightDialogueDestInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateFlightDialogueDescription)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updateFlightDialogueContentPaneLayout = new javax.swing.GroupLayout(updateFlightDialogueContentPane);
        updateFlightDialogueContentPane.setLayout(updateFlightDialogueContentPaneLayout);
        updateFlightDialogueContentPaneLayout.setHorizontalGroup(
            updateFlightDialogueContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateFlightDialogueContentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateFlightDialogueContentInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        updateFlightDialogueContentPaneLayout.setVerticalGroup(
            updateFlightDialogueContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateFlightDialogueContentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateFlightDialogueContentInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout updateFlightDialogueLayout = new javax.swing.GroupLayout(updateFlightDialogue.getContentPane());
        updateFlightDialogue.getContentPane().setLayout(updateFlightDialogueLayout);
        updateFlightDialogueLayout.setHorizontalGroup(
            updateFlightDialogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateFlightDialogueContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updateFlightDialogueLayout.setVerticalGroup(
            updateFlightDialogueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateFlightDialogueContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EAF: Eat&Fly Management");
        setBackground(new java.awt.Color(230, 230, 230));
        setFont(new java.awt.Font("Roboto Condensed", 0, 10)); // NOI18N
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1340, 800));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        navPane.setBackground(new java.awt.Color(255, 255, 255));
        navPane.setMinimumSize(new java.awt.Dimension(140, 100));
        navPane.setPreferredSize(new java.awt.Dimension(140, 300));

        overviewButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        overviewButton.setText("Overview");
        overviewButton.setBorder(null);
        overviewButton.setBorderPainted(false);
        overviewButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        overviewButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        overviewButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                overviewButtonFocusGained(evt);
            }
        });
        overviewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overviewButtonMouseClicked(evt);
            }
        });
        overviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewButtonActionPerformed(evt);
            }
        });

        flightButton.setBackground(new java.awt.Color(255, 255, 255));
        flightButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        flightButton.setText("Flights");
        flightButton.setBorderPainted(false);
        flightButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flightButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        flightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightButtonMouseClicked(evt);
            }
        });
        flightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightButtonActionPerformed(evt);
            }
        });

        dishesButton.setBackground(new java.awt.Color(255, 255, 255));
        dishesButton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        dishesButton.setText("Dishes");
        dishesButton.setBorder(null);
        dishesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dishesButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        dishesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dishesButtonActionPerformed(evt);
            }
        });

        groupLabel.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        groupLabel.setForeground(new java.awt.Color(220, 220, 220));
        groupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groupLabel.setText("Group 24");

        javax.swing.GroupLayout navPaneLayout = new javax.swing.GroupLayout(navPane);
        navPane.setLayout(navPaneLayout);
        navPaneLayout.setHorizontalGroup(
            navPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(flightButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
            .addComponent(overviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(dishesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navPaneLayout.setVerticalGroup(
            navPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPaneLayout.createSequentialGroup()
                .addComponent(overviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dishesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 446, Short.MAX_VALUE)
                .addComponent(groupLabel))
        );

        getContentPane().add(navPane);

        contentPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contentPane.setPreferredSize(new java.awt.Dimension(1200, 1147));
        contentPane.setLayout(new java.awt.CardLayout());

        flightContentPane.setName("flightContentPane"); // NOI18N

        flightTablePane.setPreferredSize(new java.awt.Dimension(600, 360));

        flightTableInnerPane.setBackground(new java.awt.Color(255, 255, 255));
        flightTableInnerPane.setMinimumSize(new java.awt.Dimension(600, 340));
        flightTableInnerPane.setPreferredSize(new java.awt.Dimension(600, 340));

        flightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight", "ID", "Start", "Destination"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        flightTable.setRowHeight(24);
        flightScrollPane.setViewportView(flightTable);

        javax.swing.GroupLayout flightTableInnerPaneLayout = new javax.swing.GroupLayout(flightTableInnerPane);
        flightTableInnerPane.setLayout(flightTableInnerPaneLayout);
        flightTableInnerPaneLayout.setHorizontalGroup(
            flightTableInnerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightTableInnerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );
        flightTableInnerPaneLayout.setVerticalGroup(
            flightTableInnerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightTableInnerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout flightTablePaneLayout = new javax.swing.GroupLayout(flightTablePane);
        flightTablePane.setLayout(flightTablePaneLayout);
        flightTablePaneLayout.setHorizontalGroup(
            flightTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, flightTablePaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(flightTableInnerPane, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
        );
        flightTablePaneLayout.setVerticalGroup(
            flightTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightTablePaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(flightTableInnerPane, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        flightOverviewPane.setPreferredSize(new java.awt.Dimension(360, 360));

        flightOverview.setBackground(new java.awt.Color(255, 255, 255));
        flightOverview.setMinimumSize(new java.awt.Dimension(0, 0));
        flightOverview.setPreferredSize(new java.awt.Dimension(543, 354));

        flightOverviewTitle.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        flightOverviewTitle.setText("Flight");

        flightOverviewActionsDelete.setBackground(new java.awt.Color(200, 20, 20));
        flightOverviewActionsDelete.setText("Delete");
        flightOverviewActionsDelete.setBorder(null);
        flightOverviewActionsDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightOverviewActionsDeleteActionPerformed(evt);
            }
        });

        flightOverviewActionsUpdate.setBackground(new java.awt.Color(20, 200, 20));
        flightOverviewActionsUpdate.setForeground(new java.awt.Color(255, 255, 255));
        flightOverviewActionsUpdate.setText("Update");
        flightOverviewActionsUpdate.setToolTipText("You can update the flight by directly editing the table as well.");
        flightOverviewActionsUpdate.setBorder(null);
        flightOverviewActionsUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightOverviewActionsUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout flightOverviewActionsFeedbackPaneLayout = new javax.swing.GroupLayout(flightOverviewActionsFeedbackPane);
        flightOverviewActionsFeedbackPane.setLayout(flightOverviewActionsFeedbackPaneLayout);
        flightOverviewActionsFeedbackPaneLayout.setHorizontalGroup(
            flightOverviewActionsFeedbackPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        flightOverviewActionsFeedbackPaneLayout.setVerticalGroup(
            flightOverviewActionsFeedbackPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout flightOverviewActionsLayout = new javax.swing.GroupLayout(flightOverviewActions);
        flightOverviewActions.setLayout(flightOverviewActionsLayout);
        flightOverviewActionsLayout.setHorizontalGroup(
            flightOverviewActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightOverviewActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(flightOverviewActionsUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(flightOverviewActionsDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(flightOverviewActionsFeedbackPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        flightOverviewActionsLayout.setVerticalGroup(
            flightOverviewActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, flightOverviewActionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(flightOverviewActionsFeedbackPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(flightOverviewActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightOverviewActionsUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightOverviewActionsDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        flightOverviewIDLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        flightOverviewIDLabel.setText("ID:");

        flightOverviewIDContent.setToolTipText("");

        javax.swing.GroupLayout flightOverviewIDLayout = new javax.swing.GroupLayout(flightOverviewID);
        flightOverviewID.setLayout(flightOverviewIDLayout);
        flightOverviewIDLayout.setHorizontalGroup(
            flightOverviewIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightOverviewIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightOverviewIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightOverviewIDContent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        flightOverviewIDLayout.setVerticalGroup(
            flightOverviewIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightOverviewIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(flightOverviewIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flightOverviewIDContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flightOverviewIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        flightOverviewStartLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        flightOverviewStartLabel.setText("Start Airport: ");

        flightOverviewStartContent.setToolTipText("");

        flightOverviewDestContent.setToolTipText("");

        flightOverviewDestLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        flightOverviewDestLabel.setText("Destination:");

        javax.swing.GroupLayout flightOverviewStartDestLayout = new javax.swing.GroupLayout(flightOverviewStartDest);
        flightOverviewStartDest.setLayout(flightOverviewStartDestLayout);
        flightOverviewStartDestLayout.setHorizontalGroup(
            flightOverviewStartDestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightOverviewStartDestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightOverviewStartLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(flightOverviewStartContent, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightOverviewDestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(flightOverviewDestContent, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        flightOverviewStartDestLayout.setVerticalGroup(
            flightOverviewStartDestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, flightOverviewStartDestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(flightOverviewStartDestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(flightOverviewDestContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flightOverviewDestLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flightOverviewStartLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(flightOverviewStartContent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout flightOverviewContentLayout = new javax.swing.GroupLayout(flightOverviewContent);
        flightOverviewContent.setLayout(flightOverviewContentLayout);
        flightOverviewContentLayout.setHorizontalGroup(
            flightOverviewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(flightOverviewActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(flightOverviewID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(flightOverviewStartDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        flightOverviewContentLayout.setVerticalGroup(
            flightOverviewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, flightOverviewContentLayout.createSequentialGroup()
                .addComponent(flightOverviewID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightOverviewStartDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(flightOverviewActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout flightOverviewLayout = new javax.swing.GroupLayout(flightOverview);
        flightOverview.setLayout(flightOverviewLayout);
        flightOverviewLayout.setHorizontalGroup(
            flightOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(flightOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flightOverviewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(flightOverviewLayout.createSequentialGroup()
                        .addComponent(flightOverviewTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        flightOverviewLayout.setVerticalGroup(
            flightOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flightOverviewTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flightOverviewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout flightOverviewPaneLayout = new javax.swing.GroupLayout(flightOverviewPane);
        flightOverviewPane.setLayout(flightOverviewPaneLayout);
        flightOverviewPaneLayout.setHorizontalGroup(
            flightOverviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightOverviewPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(flightOverview, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        flightOverviewPaneLayout.setVerticalGroup(
            flightOverviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightOverviewPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(flightOverview, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addGap(200, 200, 200))
        );

        javax.swing.GroupLayout flightContentPaneLayout = new javax.swing.GroupLayout(flightContentPane);
        flightContentPane.setLayout(flightContentPaneLayout);
        flightContentPaneLayout.setHorizontalGroup(
            flightContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(flightContentPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(flightTablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(flightOverviewPane, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
        );
        flightContentPaneLayout.setVerticalGroup(
            flightContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(flightOverviewPane, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
            .addComponent(flightTablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        contentPane.add(flightContentPane, "flightContentPane");
        flightContentPane.getAccessibleContext().setAccessibleName("flightContentPane");

        overviewContentPane.setName("overviewContentPane"); // NOI18N
        overviewContentPane.setLayout(new java.awt.GridLayout(1, 2, 50, 0));

        overviewPane.setPreferredSize(new java.awt.Dimension(500, 360));

        overviewContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout overviewContentLayout = new javax.swing.GroupLayout(overviewContent);
        overviewContent.setLayout(overviewContentLayout);
        overviewContentLayout.setHorizontalGroup(
            overviewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        overviewContentLayout.setVerticalGroup(
            overviewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout overviewPaneLayout = new javax.swing.GroupLayout(overviewPane);
        overviewPane.setLayout(overviewPaneLayout);
        overviewPaneLayout.setHorizontalGroup(
            overviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(overviewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        overviewPaneLayout.setVerticalGroup(
            overviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(overviewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        overviewContentPane.add(overviewPane);

        quickAccess.setBackground(new java.awt.Color(255, 255, 255));
        quickAccess.setPreferredSize(new java.awt.Dimension(360, 140));

        quickAcessLabel.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        quickAcessLabel.setText("Quick Access");

        quickAccessTabPane.setBackground(new java.awt.Color(255, 255, 255));
        quickAccessTabPane.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        quickAccessFlightTab.setBackground(new java.awt.Color(255, 255, 255));

        quickAccessFlightCreateButton.setBackground(new java.awt.Color(20, 200, 20));
        quickAccessFlightCreateButton.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        quickAccessFlightCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        quickAccessFlightCreateButton.setText("Create Flight");
        quickAccessFlightCreateButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 200, 20), 4, true));
        quickAccessFlightCreateButton.setBorderPainted(false);
        quickAccessFlightCreateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quickAccessFlightCreateButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        quickAccessFlightCreateButton.setDoubleBuffered(true);
        quickAccessFlightCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickAccessFlightCreateButtonActionPerformed(evt);
            }
        });

        quickAccessFlightDeleteButton.setBackground(new java.awt.Color(200, 20, 20));
        quickAccessFlightDeleteButton.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        quickAccessFlightDeleteButton.setText("Delete Flight");
        quickAccessFlightDeleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 200, 20), 4, true));
        quickAccessFlightDeleteButton.setBorderPainted(false);
        quickAccessFlightDeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quickAccessFlightDeleteButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        quickAccessFlightDeleteButton.setDoubleBuffered(true);
        quickAccessFlightDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickAccessFlightDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quickAccessFlightTabLayout = new javax.swing.GroupLayout(quickAccessFlightTab);
        quickAccessFlightTab.setLayout(quickAccessFlightTabLayout);
        quickAccessFlightTabLayout.setHorizontalGroup(
            quickAccessFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickAccessFlightTabLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(quickAccessFlightCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quickAccessFlightDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        quickAccessFlightTabLayout.setVerticalGroup(
            quickAccessFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quickAccessFlightTabLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(quickAccessFlightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quickAccessFlightCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quickAccessFlightDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        quickAccessTabPane.addTab("   Flights   ", quickAccessFlightTab);

        quickAccessDishTab.setBackground(new java.awt.Color(255, 255, 255));

        quickAccessDishCreateButton.setBackground(new java.awt.Color(20, 200, 20));
        quickAccessDishCreateButton.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        quickAccessDishCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        quickAccessDishCreateButton.setText("Create Dish");
        quickAccessDishCreateButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 200, 20), 4, true));
        quickAccessDishCreateButton.setBorderPainted(false);
        quickAccessDishCreateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quickAccessDishCreateButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        quickAccessDishCreateButton.setDoubleBuffered(true);
        quickAccessDishCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickAccessDishCreateButtonActionPerformed(evt);
            }
        });

        quickAccessDishDeleteButton.setBackground(new java.awt.Color(200, 20, 20));
        quickAccessDishDeleteButton.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        quickAccessDishDeleteButton.setText("Delete Dish");
        quickAccessDishDeleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 200, 20), 4, true));
        quickAccessDishDeleteButton.setBorderPainted(false);
        quickAccessDishDeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quickAccessDishDeleteButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        quickAccessDishDeleteButton.setDoubleBuffered(true);
        quickAccessDishDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickAccessDishDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quickAccessDishTabLayout = new javax.swing.GroupLayout(quickAccessDishTab);
        quickAccessDishTab.setLayout(quickAccessDishTabLayout);
        quickAccessDishTabLayout.setHorizontalGroup(
            quickAccessDishTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickAccessDishTabLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(quickAccessDishCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quickAccessDishDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        quickAccessDishTabLayout.setVerticalGroup(
            quickAccessDishTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quickAccessDishTabLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(quickAccessDishTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quickAccessDishCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quickAccessDishDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        quickAccessTabPane.addTab("   Dishes   ", quickAccessDishTab);

        javax.swing.GroupLayout quickAccessLayout = new javax.swing.GroupLayout(quickAccess);
        quickAccess.setLayout(quickAccessLayout);
        quickAccessLayout.setHorizontalGroup(
            quickAccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickAccessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quickAcessLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(quickAccessTabPane)
        );
        quickAccessLayout.setVerticalGroup(
            quickAccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickAccessLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(quickAcessLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quickAccessTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        quickAccessTabPane.getAccessibleContext().setAccessibleName("Flights");

        lastTasks.setBackground(new java.awt.Color(255, 255, 255));
        lastTasks.setPreferredSize(new java.awt.Dimension(360, 200));

        taskLabel.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        taskLabel.setText("Your task history");

        taskScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        taskScrollPane.setBorder(null);
        taskScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        taskScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        taskScrollPane.setAutoscrolls(true);
        taskScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        taskScrollPane.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        taskScrollPane.setPreferredSize(new java.awt.Dimension(353, 170));

        taskPanel.setBackground(new java.awt.Color(255, 255, 255));

        taskPanelContent.setText("No tasks performed yet...");

        javax.swing.GroupLayout taskPanelLayout = new javax.swing.GroupLayout(taskPanel);
        taskPanel.setLayout(taskPanelLayout);
        taskPanelLayout.setHorizontalGroup(
            taskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(taskPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        taskPanelLayout.setVerticalGroup(
            taskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        taskPanel1.setBackground(new java.awt.Color(255, 255, 255));

        taskPanelContent1.setText("No tasks performed yet...");

        javax.swing.GroupLayout taskPanel1Layout = new javax.swing.GroupLayout(taskPanel1);
        taskPanel1.setLayout(taskPanel1Layout);
        taskPanel1Layout.setHorizontalGroup(
            taskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(taskPanelContent1, javax.swing.GroupLayout.DEFAULT_SIZE, 1669, Short.MAX_VALUE)
                .addContainerGap())
        );
        taskPanel1Layout.setVerticalGroup(
            taskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskPanelContent1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        taskPanel2.setBackground(new java.awt.Color(255, 255, 255));

        taskPanelContent2.setText("No tasks performed yet...");

        javax.swing.GroupLayout taskPanel2Layout = new javax.swing.GroupLayout(taskPanel2);
        taskPanel2.setLayout(taskPanel2Layout);
        taskPanel2Layout.setHorizontalGroup(
            taskPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(taskPanelContent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        taskPanel2Layout.setVerticalGroup(
            taskPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskPanelContent2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        taskPanel3.setBackground(new java.awt.Color(255, 255, 255));

        taskPanelContent3.setText("No tasks performed yet...");

        javax.swing.GroupLayout taskPanel3Layout = new javax.swing.GroupLayout(taskPanel3);
        taskPanel3.setLayout(taskPanel3Layout);
        taskPanel3Layout.setHorizontalGroup(
            taskPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(taskPanelContent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        taskPanel3Layout.setVerticalGroup(
            taskPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskPanelContent3, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        taskPanel4.setBackground(new java.awt.Color(255, 255, 255));

        taskPanelContent4.setText("No tasks performed yet...");

        javax.swing.GroupLayout taskPanel4Layout = new javax.swing.GroupLayout(taskPanel4);
        taskPanel4.setLayout(taskPanel4Layout);
        taskPanel4Layout.setHorizontalGroup(
            taskPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(taskPanelContent4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        taskPanel4Layout.setVerticalGroup(
            taskPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskPanelContent4, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout taskScrollPanelLayout = new javax.swing.GroupLayout(taskScrollPanel);
        taskScrollPanel.setLayout(taskScrollPanelLayout);
        taskScrollPanelLayout.setHorizontalGroup(
            taskScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taskPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taskPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taskPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taskPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        taskScrollPanelLayout.setVerticalGroup(
            taskScrollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskScrollPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        taskScrollPane.setViewportView(taskScrollPanel);

        javax.swing.GroupLayout lastTasksLayout = new javax.swing.GroupLayout(lastTasks);
        lastTasks.setLayout(lastTasksLayout);
        lastTasksLayout.setHorizontalGroup(
            lastTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(taskScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lastTasksLayout.setVerticalGroup(
            lastTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taskScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout accessTaskPanelLayout = new javax.swing.GroupLayout(accessTaskPanel);
        accessTaskPanel.setLayout(accessTaskPanelLayout);
        accessTaskPanelLayout.setHorizontalGroup(
            accessTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accessTaskPanelLayout.createSequentialGroup()
                .addGroup(accessTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastTasks, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(quickAccess, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        accessTaskPanelLayout.setVerticalGroup(
            accessTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accessTaskPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lastTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(quickAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        overviewContentPane.add(accessTaskPanel);

        contentPane.add(overviewContentPane, "overviewContentPane");
        overviewContentPane.getAccessibleContext().setAccessibleName("overviewContentPane");

        dishContentPane.setName("dishContentPane"); // NOI18N
        dishContentPane.setLayout(new java.awt.GridLayout(1, 0));

        dishTablePane.setPreferredSize(new java.awt.Dimension(500, 360));

        dishTable.setBackground(new java.awt.Color(255, 255, 255));
        dishTable.setMinimumSize(new java.awt.Dimension(600, 340));
        dishTable.setPreferredSize(new java.awt.Dimension(600, 340));

        javax.swing.GroupLayout dishTableLayout = new javax.swing.GroupLayout(dishTable);
        dishTable.setLayout(dishTableLayout);
        dishTableLayout.setHorizontalGroup(
            dishTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dishTableLayout.setVerticalGroup(
            dishTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dishTablePaneLayout = new javax.swing.GroupLayout(dishTablePane);
        dishTablePane.setLayout(dishTablePaneLayout);
        dishTablePaneLayout.setHorizontalGroup(
            dishTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dishTablePaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(dishTable, javax.swing.GroupLayout.PREFERRED_SIZE, 563, Short.MAX_VALUE))
        );
        dishTablePaneLayout.setVerticalGroup(
            dishTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishTablePaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dishTable, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        dishContentPane.add(dishTablePane);

        dishOverviewPane.setPreferredSize(new java.awt.Dimension(360, 360));

        dishOverview.setBackground(new java.awt.Color(255, 255, 255));

        dishOverviewTitle.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        dishOverviewTitle.setText("Dish");

        javax.swing.GroupLayout dishOverviewLayout = new javax.swing.GroupLayout(dishOverview);
        dishOverview.setLayout(dishOverviewLayout);
        dishOverviewLayout.setHorizontalGroup(
            dishOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dishOverviewTitle)
                .addContainerGap(501, Short.MAX_VALUE))
        );
        dishOverviewLayout.setVerticalGroup(
            dishOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dishOverviewTitle)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dishOverviewPaneLayout = new javax.swing.GroupLayout(dishOverviewPane);
        dishOverviewPane.setLayout(dishOverviewPaneLayout);
        dishOverviewPaneLayout.setHorizontalGroup(
            dishOverviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dishOverviewPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dishOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        dishOverviewPaneLayout.setVerticalGroup(
            dishOverviewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishOverviewPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dishOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(200, 200, 200))
        );

        dishContentPane.add(dishOverviewPane);

        contentPane.add(dishContentPane, "dishContentPane");
        dishContentPane.getAccessibleContext().setAccessibleName("dishContentPane");

        getContentPane().add(contentPane);

        menuBar.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dishesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dishesButtonActionPerformed
        GuiUtils.changeNavbar(dishesButton, navPane);
        GuiUtils.swapActivePane(dishContentPane);
    }//GEN-LAST:event_dishesButtonActionPerformed

    private void flightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightButtonActionPerformed
        GuiUtils.changeNavbar(flightButton, navPane);
        GuiUtils.swapActivePane(flightContentPane);
    }//GEN-LAST:event_flightButtonActionPerformed

    private void overviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewButtonActionPerformed
        GuiUtils.changeNavbar(overviewButton, navPane);
        GuiUtils.swapActivePane(overviewContentPane);
    }//GEN-LAST:event_overviewButtonActionPerformed

    private void overviewButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_overviewButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_overviewButtonFocusGained

    private void flightButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightButtonMouseClicked

    }//GEN-LAST:event_flightButtonMouseClicked

    private void overviewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overviewButtonMouseClicked

    }//GEN-LAST:event_overviewButtonMouseClicked

    private void quickAccessDishDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickAccessDishDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quickAccessDishDeleteButtonActionPerformed

    private void quickAccessDishCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickAccessDishCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quickAccessDishCreateButtonActionPerformed

    private void quickAccessFlightDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickAccessFlightDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quickAccessFlightDeleteButtonActionPerformed

    private void quickAccessFlightCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickAccessFlightCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quickAccessFlightCreateButtonActionPerformed

    private void flightOverviewActionsDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightOverviewActionsDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightOverviewActionsDeleteActionPerformed

    private void flightOverviewActionsUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightOverviewActionsUpdateActionPerformed
        updateFlightDialogue.setVisible(true);
        updateFlightDialogue.setLocationRelativeTo(flightOverviewPane);
    }//GEN-LAST:event_flightOverviewActionsUpdateActionPerformed

    private void updateFlightDialogueNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFlightDialogueNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateFlightDialogueNameInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            // Set System L&F
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());

        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                inst = new Main().init();
                GuiUtils.initMain(inst);
            }
        });

    }

    //Setup method. Only overview pane should be visible when the application starts
    // We chose this design choise so that it is easy to add more content to the frame.
    private Main init() {  
        // Get the layout manager defined in the netbeans designer
        layoutManager = (CardLayout) contentPane.getLayout();
        
        // show the overview panel since this is the first information that
        // the user should see after starting the application
        layoutManager.show(contentPane, "overviewContentPane");
        //setup additional Listeners that cannot be created with Netbeans Desginer
        setupCustomListeners();
        
        // Start DataBase: Does all the deserialisation
        dataBase = new DataBase(this);
        
        // Setup the flight table controller
        flightTableController = new FlightTableController(this, flightTable);
        // populate the table
        flightTableController.populate();
        flightTableController.listen();
        
        pack();
        this.setSize(1450, 660);
        // set the frame's visibility
        setVisible(true);
        // return the modified object
        return this;
    }
    
    
    
    // called in the init method. Used to setup all additional EventListeners
    private void setupCustomListeners() {
        createFlightSelectionListener();
    }
    
    // Set the seletcion listener for the flight table
    private void createFlightSelectionListener() {
        
    }
    
    
    
        
    // Getter and setter
    public DataBase getDataBase() {
        return dataBase;
    }
    
    public CardLayout getLayoutManager() {
        return layoutManager;
    }
    
    public JPanel getCustomContentPane() {
        return contentPane;
    }
    
    // Getters for flight overview label
    public JLabel getFlightOverviewIDContent() {
        return flightOverviewIDContent;
    }
    
    public JLabel getFlightOverviewStartContent() {
        return flightOverviewStartContent;
    }
    
     public JLabel getFlightOverviewDestContent() {
        return flightOverviewDestContent;
    }
     
    public JLabel getFlightOverviewTitle() {
        return flightOverviewTitle;
    }
    
    // Database reference
   private DataBase dataBase;
    
    private FlightTableController flightTableController;
    // Layout 
    private CardLayout layoutManager;
    // Static reference to this runnable instance
    public static Main inst;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accessTaskPanel;
    private javax.swing.JPanel contentPane;
    private javax.swing.JPanel dishContentPane;
    private javax.swing.JPanel dishOverview;
    private javax.swing.JPanel dishOverviewPane;
    private javax.swing.JLabel dishOverviewTitle;
    private javax.swing.JPanel dishTable;
    private javax.swing.JPanel dishTablePane;
    private javax.swing.JButton dishesButton;
    private javax.swing.JButton flightButton;
    private javax.swing.JPanel flightContentPane;
    private javax.swing.JPanel flightOverview;
    private javax.swing.JPanel flightOverviewActions;
    private javax.swing.JButton flightOverviewActionsDelete;
    private javax.swing.JPanel flightOverviewActionsFeedbackPane;
    private javax.swing.JButton flightOverviewActionsUpdate;
    private javax.swing.JPanel flightOverviewContent;
    private javax.swing.JLabel flightOverviewDestContent;
    private javax.swing.JLabel flightOverviewDestLabel;
    private javax.swing.JPanel flightOverviewID;
    private javax.swing.JLabel flightOverviewIDContent;
    private javax.swing.JLabel flightOverviewIDLabel;
    private javax.swing.JPanel flightOverviewPane;
    private javax.swing.JLabel flightOverviewStartContent;
    private javax.swing.JPanel flightOverviewStartDest;
    private javax.swing.JLabel flightOverviewStartLabel;
    private javax.swing.JLabel flightOverviewTitle;
    private javax.swing.JScrollPane flightScrollPane;
    private javax.swing.JTable flightTable;
    private javax.swing.JPanel flightTableInnerPane;
    private javax.swing.JPanel flightTablePane;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel lastTasks;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel navPane;
    private javax.swing.JButton overviewButton;
    private javax.swing.JPanel overviewContent;
    private javax.swing.JPanel overviewContentPane;
    private javax.swing.JPanel overviewPane;
    private javax.swing.JPanel quickAccess;
    private javax.swing.JButton quickAccessDishCreateButton;
    private javax.swing.JButton quickAccessDishDeleteButton;
    private javax.swing.JPanel quickAccessDishTab;
    private javax.swing.JButton quickAccessFlightCreateButton;
    private javax.swing.JButton quickAccessFlightDeleteButton;
    private javax.swing.JPanel quickAccessFlightTab;
    private javax.swing.JTabbedPane quickAccessTabPane;
    private javax.swing.JLabel quickAcessLabel;
    private javax.swing.JLabel taskLabel;
    private javax.swing.JPanel taskPanel;
    private javax.swing.JPanel taskPanel1;
    private javax.swing.JPanel taskPanel2;
    private javax.swing.JPanel taskPanel3;
    private javax.swing.JPanel taskPanel4;
    private javax.swing.JLabel taskPanelContent;
    private javax.swing.JLabel taskPanelContent1;
    private javax.swing.JLabel taskPanelContent2;
    private javax.swing.JLabel taskPanelContent3;
    private javax.swing.JLabel taskPanelContent4;
    private javax.swing.JScrollPane taskScrollPane;
    private javax.swing.JPanel taskScrollPanel;
    private javax.swing.JDialog updateFlightDialogue;
    private javax.swing.JPanel updateFlightDialogueContentInner;
    private javax.swing.JPanel updateFlightDialogueContentPane;
    private javax.swing.JLabel updateFlightDialogueDescription;
    private javax.swing.JLabel updateFlightDialogueDest;
    private javax.swing.JTextField updateFlightDialogueDestInput;
    private javax.swing.JLabel updateFlightDialogueID;
    private javax.swing.JTextField updateFlightDialogueIDInput;
    private javax.swing.JLabel updateFlightDialogueName;
    private javax.swing.JTextField updateFlightDialogueNameInput;
    private javax.swing.JLabel updateFlightDialogueStart;
    private javax.swing.JTextField updateFlightDialogueStartInput;
    private javax.swing.JLabel updateFlightDialogueTitle;
    // End of variables declaration//GEN-END:variables
}
